<?php

/**
 * BaseLecture
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $activity
 * @property string $module
 * @property string $type
 * @property string $room
 * @property string $lecturer
 * @property timestamp $start_at
 * @property timestamp $end_at
 * @property sfGuardUser $User
 * 
 * @method integer     getUserId()   Returns the current record's "user_id" value
 * @method string      getActivity() Returns the current record's "activity" value
 * @method string      getModule()   Returns the current record's "module" value
 * @method string      getType()     Returns the current record's "type" value
 * @method string      getRoom()     Returns the current record's "room" value
 * @method string      getLecturer() Returns the current record's "lecturer" value
 * @method timestamp   getStartAt()  Returns the current record's "start_at" value
 * @method timestamp   getEndAt()    Returns the current record's "end_at" value
 * @method sfGuardUser getUser()     Returns the current record's "User" value
 * @method Lecture     setUserId()   Sets the current record's "user_id" value
 * @method Lecture     setActivity() Sets the current record's "activity" value
 * @method Lecture     setModule()   Sets the current record's "module" value
 * @method Lecture     setType()     Sets the current record's "type" value
 * @method Lecture     setRoom()     Sets the current record's "room" value
 * @method Lecture     setLecturer() Sets the current record's "lecturer" value
 * @method Lecture     setStartAt()  Sets the current record's "start_at" value
 * @method Lecture     setEndAt()    Sets the current record's "end_at" value
 * @method Lecture     setUser()     Sets the current record's "User" value
 * 
 * @package    uwe
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLecture extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lecture');
        $this->hasColumn('user_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('activity', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('module', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('room', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lecturer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('start_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('end_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => '',
             ));

        $this->option('orderBy', 'start_at ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}