<?php

/**
 * BaseCurrencyCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $currency_code
 * @property integer $country_id
 * @property Currency $Currency
 * @property Country $Country
 * 
 * @method string          getCurrencyCode()  Returns the current record's "currency_code" value
 * @method integer         getCountryId()     Returns the current record's "country_id" value
 * @method Currency        getCurrency()      Returns the current record's "Currency" value
 * @method Country         getCountry()       Returns the current record's "Country" value
 * @method CurrencyCountry setCurrencyCode()  Sets the current record's "currency_code" value
 * @method CurrencyCountry setCountryId()     Sets the current record's "country_id" value
 * @method CurrencyCountry setCurrency()      Sets the current record's "Currency" value
 * @method CurrencyCountry setCountry()       Sets the current record's "Country" value
 * 
 * @package    currency-converter
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurrencyCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('currency_country');
        $this->hasColumn('currency_code', 'string', 3, array(
             'type' => 'string',
             'primary' => true,
             'length' => 3,
             ));
        $this->hasColumn('country_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 11,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Currency', array(
             'local' => 'currency_code',
             'foreign' => 'code'));

        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));
    }
}