<?php

/**
 * BaseCurrencyRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $from_code
 * @property string $to_code
 * @property double $rate
 * 
 * @method string       getFromCode()  Returns the current record's "from_code" value
 * @method string       getToCode()    Returns the current record's "to_code" value
 * @method double       getRate()      Returns the current record's "rate" value
 * @method CurrencyRate setFromCode()  Sets the current record's "from_code" value
 * @method CurrencyRate setToCode()    Sets the current record's "to_code" value
 * @method CurrencyRate setRate()      Sets the current record's "rate" value
 * 
 * @package    currency-converter
 * @subpackage model
 * @author     Steve Lacey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurrencyRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('currency_rate');
        $this->hasColumn('from_code', 'string', 3, array(
             'type' => 'string',
             'primary' => true,
             'length' => 3,
             ));
        $this->hasColumn('to_code', 'string', 3, array(
             'type' => 'string',
             'primary' => true,
             'length' => 3,
             ));
        $this->hasColumn('rate', 'double', 20, array(
             'type' => 'double',
             'scale' => 18,
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}