<?php

/**
 * CurrencyRateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurrencyRateTable extends Doctrine_Table {
  /**
   * Returns an instance of this class.
   *
   * @return object CurrencyRateTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('CurrencyRate');
  }

  public function getCurrencyRate(Currency $from, Currency $to) {
    $currency_rate = $this->findOneByFromCodeAndToCode($from, $to);

    if(!$currency_rate instanceOf CurrencyRate) {
      $currency_rate = new CurrencyRate();
      $currency_rate->setFromCode($from->getCode());
      $currency_rate->setToCode($to->getCode());
    }

    return $currency_rate;
  }

  public function findOneByFromCodeAndToCode($from, $to) {
    return Doctrine_Query::create()->
      from('CurrencyRate')->
      where('from_code = ?', $from->getCode())->
      andWhere('to_code = ?', $to->getCode())->
      fetchOne();
  }
}