<?php

/**
 * CurrencyCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CurrencyCountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CurrencyCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CurrencyCountry');
    }
}