all:
  convert:
    params:
      - amnt
      - from
      - to
    decimal_amount: 2  # decimal places
    decimal_result: 5  # decimal places
    decimal_stored: 20 # decimal places

  error:
    1000: URL not recognized
    1100: Required parameter is missing
    1200: Parameter not recognized
    2000: Currency type not recognized
    2100: Currency amount must be a decimal number
    3000: Service currently unavailable
    3100: Error in service
    4000: Currency rate unavailable

  cache:
    moneyconverter: %sf_cache_dir%/moneyconverter.rss
    bloomberg: %sf_cache_dir%/bloomberg.js
    database: 60 # minutes
    file: 120 # minutes

  source:
    currencies: http://en.wikipedia.org/wiki/Special:Export/ISO_4217
    countries:  http://www.xe.com/ucc/full

    rates_rss:  http://themoneyconverter.com
    rates_js:   http://www.bloomberg.com/js/calculators/currdata.js

  currency:
    base: USD

  currency_alias:
    ZWL: ZWD # The ISO 4217 spec lists the Zimbabwean Dollar incorrectly, everywhere else accepts it as ZWD.

  web:
    proxy: cache.uwe.ac.uk:8080

dev:
  web:
    proxy: # Remove UWE Proxy