all:
  convert:
    cache: 60 # minutes
    params:
      - amnt
      - from
      - to
  error:
    1000: URL not recognized
    1100: Required parameter is missing
    1200: Parameter not recognized
    2000: Currency type not recognized
    2100: Currency amount must be a decimal number
    3000: Service currently unavailable
    3100: Error in service
  uwe:
    proxy: cache.uwe.ac.uk:8080

dev:
  uwe:
    proxy: