homepage:
  class: sfRoute
  url:   /
  param:
    module: convert
    action: index

convert:
  class: sfRoute
  url:   /:amnt/from/:from/to/:to
  param:
    module: convert
    action: index
  options:
    segment_separators: [/] # remove . which is used to define decimals

task:
  class: sfRoute
  url:   /task/:action
  param:
    module: task
    action: cc
