homepage:
  class: sfRoute
  url:   /
  param:
    module: convert
    action: index
    sf_format: xml
  requirements:
    amnt: \w+
    from: \w+
    to: \w+

html:
  class: sfRoute
  url:   /convert.html
  param:
    module: convert
    action: test
  requirements:
    amnt: \w+
    from: \w+
    to: \w+

convert_improved:
  class: sfRoute
  url:   /:amount/from/:from/to/:to
  param:
    module: convert
    action: index
    sf_format: xml
  requirements:
    amount: \w+
    from: \w+
    to: \w+

task:
  class: sfRoute
  url:   /task/:action
  param:
    module: task
    action: cc