all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      persistent: true
      pooling: true
      attributes:
        use_dql_callbacks: true

dev:
  doctrine:
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=cc_dev'
      username: cc_dev
      password: changeme

demo:
  doctrine:
    param:
      dsn: 'mysql-alternative-pdo:host=shares;dbname=slacey'
      username: slacey
      password: changeme

live:
  doctrine:
    param:
      dsn: 'mysql-alternative-pdo:host=shares;dbname=slacey'
      username: slacey
      password: changeme
