<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('currency', array(
             'code' => 
             array(
              'type' => 'string',
              'primary' => '1',
              'length' => '3',
             ),
             'number' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '3',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'locations' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'digits' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '1',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'code',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('currency');
    }
}