Currency:
  actAs:
    Timestampable: ~
  columns:
    code:
      type: string(3)
      primary: true
    number:
      type: string(3)
      notnull: true
    name:
      type: string(255)
      notnull: true
    digits:
      type: integer(1)
      notnull: true
  options:
    orderBy: name ASC
  relations:
    Countries:
      class: Country
      refClass: CurrencyCountry
      local: currency_code
      foreign: country_id
      foreignAlias: Currencies

CurrencyCountry:
  columns:
    currency_code:
      type: string(3)
      primary: true
    country_id:
      type: integer(11)
      primary: true
  relations:
    Currency:
      class: Currency
      local: currency_code
      foreign: code
    Country:
      class: Country
      local: country_id
      foreign: id

Country:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
  options:
    orderBy: name ASC
  relations:
    Currencies:
      class: Currency
      refClass: CurrencyCountry
      local: country_id
      foreign: currency_code
      foreignAlias: Countries

CurrencyRate:
  actAs:
    Timestampable: ~
  columns:
    from_code:
      type: string(3)
      primary: true
    to_code:
      type: string(3)
      primary: true
    rate:
      type: double(40)
      scale: 20
      notnull: true